"""Draft task-aware MedLSC variant.

This file keeps the current MedLSC block structure, but replaces the hard sum over
active LoRA blocks with learned task-aware allocation weights.

Design notes:
- `allocation_projector` maps pooled hidden states to h_i.
- `allocation_keys` are separate learned parameters and are not generated by the projector.
- The fusion weights are computed from dot(h_i, key_n) / temperature.
- This routing projector is separate from multimodal `mm_projector`.
"""

import math
from typing import Optional

import torch
import torch.nn as nn
import torch.nn.functional as F


class MedLSCLayer:
    def __init__(
        self,
        lora_rank: int,
        lora_alpha: int,
        lora_dropout: float,
    ):
        self.r = lora_rank
        self.lora_alpha = lora_alpha
        if lora_dropout > 0.0:
            self.lora_dropout = nn.Dropout(p=lora_dropout)
        else:
            self.lora_dropout = lambda x: x


class LoraModule(nn.Module):
    def __init__(self, in_features, out_features, lora_rank, lora_alpha, lora_dropout):
        super().__init__()
        self.lora_A = nn.Parameter(torch.randn(lora_rank, in_features))
        self.lora_B = nn.Parameter(torch.randn(out_features, lora_rank))
        self.lora_alpha = lora_alpha
        self.r = lora_rank
        self.scaling = self.lora_alpha / self.r
        if lora_dropout > 0.0:
            self.lora_dropout = nn.Dropout(p=lora_dropout)
        else:
            self.lora_dropout = lambda x: x

    def forward(self, x):
        return (self.lora_dropout(x) @ self.lora_A.transpose(0, 1) @ self.lora_B.transpose(0, 1)) * self.scaling


class AllocationProjector(nn.Module):
    def __init__(self, in_features: int, hidden_features: int, out_features: int, trainable: bool = False):
        super().__init__()
        self.fc1 = nn.Linear(in_features, hidden_features)
        self.fc2 = nn.Linear(hidden_features, out_features)
        self.act = nn.SiLU()
        self.norm = nn.LayerNorm(out_features)

        if not trainable:
            for param in self.parameters():
                param.requires_grad = False

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        if x.dim() > 2:
            # Mirror the reference routing path: pool token dimension first.
            x = x.max(dim=1, keepdim=True).values
        x = self.fc1(x)
        x = self.fc2(x)
        x = self.act(x)
        return self.norm(x)


class Linear(nn.Linear, MedLSCLayer):
    def __init__(
        self,
        max_task: int,
        in_features: int,
        out_features: int,
        lora_rank: int = 0,
        lora_alpha: int = 1,
        lora_dropout: float = 0.0,
        fan_in_fan_out: bool = False,
        allocation_enable: bool = True,
        allocation_projector_hidden: Optional[int] = None,
        allocation_temperature: float = 1.0,
        allocation_projector_trainable: bool = True,
        routing_use_task_mask: bool = False,
        **kwargs,
    ):
        if 'adding_layers' in kwargs:
            kwargs.pop('adding_layers')

        nn.Linear.__init__(self, in_features, out_features, **kwargs)
        MedLSCLayer.__init__(self, lora_rank=lora_rank, lora_alpha=lora_alpha, lora_dropout=lora_dropout)

        self.r = lora_rank
        self.fan_in_fan_out = fan_in_fan_out
        self.max_task = max_task
        self.allocation_enable = allocation_enable
        self.allocation_temperature = float(allocation_temperature)
        self.routing_use_task_mask = routing_use_task_mask
        self.model_dim = in_features

        if allocation_projector_hidden is None:
            allocation_projector_hidden = max(1, in_features // 2)

        if lora_rank > 0:
            self.cl_lora_pool = nn.ModuleDict(
                {
                    f"task_{i}_lora": LoraModule(in_features, out_features, lora_rank, lora_alpha, lora_dropout)
                    for i in range(max_task)
                }
            )
            self.weight.requires_grad = False
            if self.bias is not None:
                self.bias.requires_grad = False
            for idx, module in enumerate(self.cl_lora_pool.values()):
                module.requires_grad_(idx == max_task - 1)

        if allocation_enable and max_task > 0:
            self.allocation_projector = AllocationProjector(
                in_features=in_features,
                hidden_features=allocation_projector_hidden,
                out_features=in_features,
                trainable=allocation_projector_trainable,
            )
            self.allocation_keys = nn.Parameter(torch.empty(max_task, in_features))
            nn.init.normal_(self.allocation_keys, mean=0.0, std=0.02)

        self.reset_parameters()
        if fan_in_fan_out:
            self.weight.data = self.weight.data.transpose(0, 1)

    def reset_parameters(self):
        nn.Linear.reset_parameters(self)
        if hasattr(self, 'cl_lora_pool'):
            for module in self.cl_lora_pool.values():
                nn.init.kaiming_uniform_(module.lora_A, a=math.sqrt(5))
                nn.init.zeros_(module.lora_B)

    def _task_indices(self, task_mask: Optional[torch.BoolTensor], device: torch.device) -> torch.Tensor:
        if (task_mask is None) or (not self.routing_use_task_mask):
            return torch.arange(self.max_task, device=device)
        active = task_mask[: self.max_task].to(device=device)
        return torch.nonzero(active, as_tuple=False).flatten()

    def _base_linear(self, x: torch.Tensor) -> torch.Tensor:
        weight = self.weight.transpose(0, 1) if self.fan_in_fan_out else self.weight
        return F.linear(x, weight, bias=self.bias)

    def _fuse_with_allocation(self, x: torch.Tensor, task_mask: Optional[torch.BoolTensor]) -> torch.Tensor:
        active_indices = self._task_indices(task_mask, device=x.device)
        if active_indices.numel() == 0:
            return self._base_linear(x)

        active_modules = [self.cl_lora_pool[f"task_{int(idx)}_lora"] for idx in active_indices.tolist()]
        active_keys = self.allocation_keys.index_select(0, active_indices)

        h_i = self.allocation_projector(x)
        scores = torch.matmul(h_i, active_keys.t())
        scores = scores.squeeze(1)

        if self.allocation_temperature > 0:
            temperature = self.allocation_temperature
        else:
            temperature = math.sqrt(float(self.model_dim))

        scores = scores / temperature
        scores = scores - torch.max(scores, dim=-1, keepdim=True).values
        weights = torch.softmax(scores, dim=-1)

        deltas = torch.stack([module(x) for module in active_modules], dim=1)
        view_shape = [weights.size(0), weights.size(1)] + [1] * (deltas.dim() - 2)
        fused_delta = (deltas * weights.view(*view_shape)).sum(dim=1)

        return self._base_linear(x) + fused_delta

    def _fuse_with_routing_weights(
        self,
        x: torch.Tensor,
        task_mask: Optional[torch.BoolTensor],
        routing_weights: torch.Tensor,
    ) -> torch.Tensor:
        active_indices = self._task_indices(task_mask, device=x.device)
        if active_indices.numel() == 0:
            return self._base_linear(x)

        active_modules = [self.cl_lora_pool[f"task_{int(idx)}_lora"] for idx in active_indices.tolist()]

        weights = routing_weights
        if weights.dim() == 1:
            weights = weights.unsqueeze(0)
        if weights.size(-1) != active_indices.numel():
            weights = weights.index_select(dim=-1, index=active_indices)
            weights = weights / weights.sum(dim=-1, keepdim=True).clamp(min=1e-6)

        deltas = torch.stack([module(x) for module in active_modules], dim=1)
        view_shape = [weights.size(0), weights.size(1)] + [1] * (deltas.dim() - 2)
        fused_delta = (deltas * weights.view(*view_shape)).sum(dim=1)

        return self._base_linear(x) + fused_delta

    def forward(
        self,
        x: torch.Tensor,
        task_mask: torch.BoolTensor = None,
        routing_weights: Optional[torch.Tensor] = None,
    ):
        if task_mask is None:
            task_mask = getattr(self, "_runtime_task_mask", None)

        if self.r <= 0:
            return self._base_linear(x)

        base = self._base_linear(x)

        if routing_weights is not None:
            return self._fuse_with_routing_weights(x, task_mask, routing_weights)

        if not self.allocation_enable or not hasattr(self, 'allocation_projector'):
            if task_mask is None:
                deltas = [module(x) for module in self.cl_lora_pool.values()]
                if len(deltas) == 0:
                    return base
                return base + torch.stack(deltas, dim=0).sum(dim=0)

            deltas = []
            num_task = 0
            for module, mask in zip(self.cl_lora_pool.values(), task_mask[: self.max_task]):
                if mask:
                    deltas.append(module(x))
                    num_task += 1

            if len(deltas) == 0:
                return base

            deltas = torch.stack(deltas, dim=0).to(device=x.device, dtype=x.dtype)
            assert deltas.shape[0] == task_mask[:num_task].shape[0]
            return base + deltas.sum(dim=0)

        return self._fuse_with_allocation(x, task_mask)


if __name__ == '__main__':
    model = Linear(
        max_task=6,
        in_features=100,
        out_features=200,
        lora_rank=64,
        lora_alpha=128,
        allocation_enable=True,
        allocation_projector_hidden=32,
        allocation_temperature=1.0,
        allocation_projector_trainable=True,
        routing_use_task_mask=False,
    )
    print(model)
    print('=' * 90)
    for n, p in model.named_parameters():
        if p.requires_grad:
            print(n)
    print('=' * 90)
    bsz = 2
    seq = 8
    x = torch.randn(bsz, seq, 100)
    task_mask = torch.zeros(1000, dtype=torch.bool)
    task_mask[:5] = True
    o = model(x, task_mask)
    print(o.shape)
