#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

CHECKPOINT_ROOT="${CHECKPOINT_ROOT:-${REPO_DIR}/checkpoints}"
LORA_CHECKPOINT_ROOT="${LORA_CHECKPOINT_ROOT:-${CHECKPOINT_ROOT}/finetune_lora_each-64-64_llava_med_v1.5}"
DATA_ROOT="${DATA_ROOT:-${REPO_DIR}/data/MedLSC}"
PYTHON_BIN="${PYTHON_BIN:-python3}"
START_FROM_TASK="${START_FROM_TASK:-0}"
# Reuse complete anchor/cache files; set to 0 to rebuild them.
export SKIP_EXISTING_ANCHORS="${SKIP_EXISTING_ANCHORS:-1}"
PORT="${PORT:-29501}"
TASK_ORDER="${TASK_ORDER:-standard}"
export PYTHONPATH="${REPO_DIR}${PYTHONPATH:+:${PYTHONPATH}}"

DEVICES="${DEVICES:-1}"
LR="${LR:-2e-4}"
GRADIENT_ACC_STEPS="${GRADIENT_ACC_STEPS:-1}"
MODEL_MAX_LENGTH="${MODEL_MAX_LENGTH:-2048}"
LORA_RANK="${LORA_RANK:-64}"
LORA_ALPHA="${LORA_ALPHA:-64}"
EPOCH_ALL="${EPOCH_ALL:-4}"

CALIBRATION_LR="${CALIBRATION_LR:-2e-5}"
CALIBRATION_EPOCH="${CALIBRATION_EPOCH:-1}"

BATCH_COVID_CXP="${BATCH_COVID_CXP:-32}"
BATCH_SLAKE_CTXR="${BATCH_SLAKE_CTXR:-32}"
BATCH_IU_XRAY="${BATCH_IU_XRAY:-16}"
BATCH_SLAKE_MRI="${BATCH_SLAKE_MRI:-32}"
BATCH_PCAM="${BATCH_PCAM:-16}"
BATCH_PATHVQA="${BATCH_PATHVQA:-16}"
BATCH_HAM_SKIN8="${BATCH_HAM_SKIN8:-16}"
BATCH_DERM="${BATCH_DERM:-16}"
BATCH_YANGXI="${BATCH_YANGXI:-16}"
BATCH_OCT_C8="${BATCH_OCT_C8:-16}"
BATCH_CERVICAL="${BATCH_CERVICAL:-16}"
BATCH_KVASIR="${BATCH_KVASIR:-16}"
BATCH_HYPERKVASIR="${BATCH_HYPERKVASIR:-16}"

SAMPLE_PER_TASK="${SAMPLE_PER_TASK:-280}"
SAMPLE_SEED="${SAMPLE_SEED:-42}"
ROUTING_GLOBAL_ENABLE="${ROUTING_GLOBAL_ENABLE:-True}"
ROUTING_ALLOCATION_ENABLE="${ROUTING_ALLOCATION_ENABLE:-True}"
ROUTING_PROJECTOR_HIDDEN="${ROUTING_PROJECTOR_HIDDEN:-64}"
ROUTING_TEMPERATURE="${ROUTING_TEMPERATURE:-1.0}"
ROUTING_PROJECTOR_TRAINABLE="${ROUTING_PROJECTOR_TRAINABLE:-True}"
ROUTING_USE_TASK_MASK="${ROUTING_USE_TASK_MASK:-False}"

KL_LOSS="${KL_LOSS:-False}"
KL_WEIGHT="${KL_WEIGHT:-1}"
ROUTER_SUPERVISION_LOSS="${ROUTER_SUPERVISION_LOSS:-True}"
ROUTER_SUPERVISION_WEIGHT="${ROUTER_SUPERVISION_WEIGHT:-1.0}"
REPLAY_PER_TASK="${REPLAY_PER_TASK:-200}"
REPLAY_SEED="${REPLAY_SEED:-42}"
EVAL_SAMPLE_SIZE="${EVAL_SAMPLE_SIZE:-200}"
EVAL_SAMPLE_SEED="${EVAL_SAMPLE_SEED:-123}"

ANCHOR_COEFFICIENT="${ANCHOR_COEFFICIENT:-0.5}"
ANCHOR_DEPARTMENT_TOPK="${ANCHOR_DEPARTMENT_TOPK:-1}"
KEY_OUTSIDE_TOPK="${KEY_OUTSIDE_TOPK:-3}"
DEPARTMENT_ANCHOR_ROUTING_ENABLE="${DEPARTMENT_ANCHOR_ROUTING_ENABLE:-1}"
DEPARTMENT_ANCHOR_FALLBACK="${DEPARTMENT_ANCHOR_FALLBACK:-oracle_task}"
DEPARTMENT_ADAPTIVE_FUSION_ENABLE="${DEPARTMENT_ADAPTIVE_FUSION_ENABLE:-1}"
export WANDB_MODE="${WANDB_MODE:-disabled}"

export EPOCH_ALL CALIBRATION_LR CALIBRATION_EPOCH
export BATCH_COVID_CXP BATCH_SLAKE_CTXR BATCH_IU_XRAY BATCH_SLAKE_MRI
export BATCH_PCAM BATCH_PATHVQA BATCH_HAM_SKIN8 BATCH_DERM
export BATCH_YANGXI BATCH_OCT_C8 BATCH_CERVICAL BATCH_KVASIR BATCH_HYPERKVASIR
export SAMPLE_PER_TASK SAMPLE_SEED
export ROUTING_GLOBAL_ENABLE ROUTING_ALLOCATION_ENABLE ROUTING_PROJECTOR_HIDDEN
export ROUTING_TEMPERATURE ROUTING_PROJECTOR_TRAINABLE ROUTING_USE_TASK_MASK
export KL_LOSS KL_WEIGHT ROUTER_SUPERVISION_LOSS ROUTER_SUPERVISION_WEIGHT
export REPLAY_PER_TASK REPLAY_SEED EVAL_SAMPLE_SIZE EVAL_SAMPLE_SEED TASK_ORDER
export ANCHOR_COEFFICIENT ANCHOR_DEPARTMENT_TOPK KEY_OUTSIDE_TOPK
export DEPARTMENT_ANCHOR_ROUTING_ENABLE DEPARTMENT_ANCHOR_FALLBACK DEPARTMENT_ADAPTIVE_FUSION_ENABLE

echo "============================================================"
echo "MedLSC V10"
echo "Stage 2"
echo "Stage 3"
echo "Operator: delta(x)=sum_i w_i * B_i(A_i(x))"
echo "Department routing init: anchor coefficient=${ANCHOR_COEFFICIENT}, adaptive=${DEPARTMENT_ADAPTIVE_FUSION_ENABLE}, anchor_topk=${ANCHOR_DEPARTMENT_TOPK}, outside_topk=${KEY_OUTSIDE_TOPK}, fallback=${DEPARTMENT_ANCHOR_FALLBACK}"
echo "No separate A/B summing; no cross-expert B_i A_j terms"
echo "Devices: ${DEVICES}; task order: ${TASK_ORDER}"
echo "Resume from task: ${START_FROM_TASK}"
echo "============================================================"

"${PYTHON_BIN}" "${REPO_DIR}/train_MedLSC.py" \
    --repo_dir "${REPO_DIR}" \
    --checkpoint_root "${CHECKPOINT_ROOT}" \
    --lora_checkpoint_root "${LORA_CHECKPOINT_ROOT}" \
    --data_root "${DATA_ROOT}" \
    --python_bin "${PYTHON_BIN}" \
    --devices "${DEVICES}" \
    --lora_rank "${LORA_RANK}" \
    --lora_alpha "${LORA_ALPHA}" \
    --learning_rate "${LR}" \
    --gradient_accumulation_steps "${GRADIENT_ACC_STEPS}" \
    --model_max_length "${MODEL_MAX_LENGTH}" \
    --port "${PORT}" \
    --start_from_task "${START_FROM_TASK}" \
    

